version: '3.8'
services:
      web:
        image: nginx:latest
        ports:
          - "8085:80"
        volumes:
          - ./html:/usr/share/nginx/html
          - ./nginx.conf:/etc/nginx/conf.d/default.conf
        container_name: nginx-1-I
        depends_on:
          - app
      db:
        image: postgres:latest
        environment:
          POSTGRES_DB: todo_db
          POSTGRES_USER: igor
          POSTGRES_PASSWORD: password
        container_name: postgres-1-I
      app:
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - "5000:5000"
        volumes:
          - ./app:/app
        container_name: flask-1-I
        depends_on:
          - db
