name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker compose build

      - name: Test Docker image
        run: |
          docker compose up -d
          sleep 15
          if docker ps -q -f name=todo-app-1 | grep -q . ; then
            echo "App container is running"
            docker exec todo-app-1 sh -c "cd /app && python -m unittest discover app/tests/ -v"
          else
            echo "App container failed to start"
            docker compose logs || echo "No logs available"
            exit 1
          fi
          docker compose down
