name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker-compose build

      - name: Test Docker image
        run: |
          docker-compose up -d
          sleep 10 # Дадим время на запуск
          if [ "$(docker ps -q -f name=todo_app_1)" ]; then
            echo "App container is running"
          else
            echo "App container failed to start"
            exit 1
          fi
          docker-compose down
