name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
      branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker compose build

      - name: Test Docker image
        run: |
          docker compose up -d
          sleep 15 # Увеличим время на запуск
          if [ "$(docker ps -q -f name=todo-app-1)" ]; then # Изменение: todo-app-1 вместо todo_app_1
            echo "App container is running"
            docker logs todo-app-1
          else
            echo "App container failed to start"
            docker logs todo-app-1 || echo "No logs available"
            exit 1
          fi
          docker compose down
